# Generated by Django 5.2.8 on 2025-11-19 18:32

import ckeditor.fields
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('client', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_app', 'Mobile App'), ('digital_marketing', 'Digital Marketing'), ('business_automation', 'Business Automation'), ('consulting', 'Business Consulting'), ('data_analytics', 'Data Analytics')], max_length=50)),
                ('short_description', models.TextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('challenge', ckeditor.fields.RichTextField(blank=True)),
                ('solution', ckeditor.fields.RichTextField(blank=True)),
                ('results', ckeditor.fields.RichTextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('main_image', models.ImageField(upload_to='projects/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='projects.project')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
